spring:
  profiles:
    active: dev
  liquibase:
    change-log: db/changelog/changelog-master.xml
  main:
    allow-bean-definition-overriding: true
  jpa:
    generate-ddl: false
application:
  cache-life-time-sec: ${cache.lifetime.sec:7200}
  security:
    secret: ${jwt.secret:Nnc5eiRDJkYpSEBNY1FmVGpXblpyNHU3eCFBJUQqRy1LYU5kUmdVa1hwMnM1djh5L0I/RShIK01iUWVTaFZtWQ==}
    token-validity-in-seconds: ${jwt.life.time.sec:86400}
